<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ActeMedical;
use Illuminate\Support\Str;

class ActeMedicalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        ActeMedical::insert([
            [
                'id' => Str::uuid(),
                'code' => 'IRM01',
                'designation' => 'IRM',
                'categorie' => 'soins ambulatoires',
                'type' => 'IRM',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 90000.00,
                'frequence_plafond' => 'par acte',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'SI01',
                'designation' => 'Soins infirmiers',
                'categorie' => 'soins ambulatoires',
                'type' => 'Soins infirmiers',
                'sous_type' => 'clinique privée',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 3000.00,
                'frequence_plafond' => 'par acte',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'CG01',
                'designation' => 'Consultation généralistes',
                'categorie' => 'soins ambulatoires',
                'type' => 'Consultation',
                'sous_type' => 'généralistes',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 7500.00,
                'frequence_plafond' => 'par consultation',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'FHPUB01',
                'designation' => 'Frais d’hospitalisation (public)',
                'categorie' => 'hospitalisation',
                'type' => 'Frais d’hospitalisation',
                'sous_type' => 'public',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 15000.00,
                'frequence_plafond' => 'par nuitée',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'FHPRIV01',
                'designation' => 'Frais d’hospitalisation (privé)',
                'categorie' => 'hospitalisation',
                'type' => 'Frais d’hospitalisation',
                'sous_type' => 'privé',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 20000.00,
                'frequence_plafond' => 'par nuitée',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'AMHOS01',
                'designation' => 'Actes médicaux au cours d’une hospitalisation',
                'categorie' => 'hospitalisation',
                'type' => 'Actes médicaux',
                'sous_type' => 'hospitalisation',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 100000.00,
                'frequence_plafond' => 'par an',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'ACS01',
                'designation' => 'Actes chirurgicaux au cours d’une hospitalisation',
                'categorie' => 'hospitalisation',
                'type' => 'Actes chirurgicaux',
                'sous_type' => 'hospitalisation',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 200000.00,
                'frequence_plafond' => 'par an',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'AS01',
                'designation' => 'Analyses simples',
                'categorie' => 'analyse biomédicale',
                'type' => 'Analyses',
                'sous_type' => 'simple',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 10000.00,
                'frequence_plafond' => 'par analyse',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'ASS01',
                'designation' => 'Analyses spécifiques',
                'categorie' => 'analyse biomédicale',
                'type' => 'Analyses',
                'sous_type' => 'spécifiques',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 20000.00,
                'frequence_plafond' => 'par analyse',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'RS01',
                'designation' => 'Radiologies standard',
                'categorie' => 'radiologie',
                'type' => 'Radiologies',
                'sous_type' => 'standard',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 10000.00,
                'frequence_plafond' => 'par radiologie',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'RSP01',
                'designation' => 'Radiologies et échographies spécifiques',
                'categorie' => 'radiologie',
                'type' => 'Radiologies',
                'sous_type' => 'spécifiques',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 20000.00,
                'frequence_plafond' => 'par radiologie',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'ECG01',
                'designation' => 'Electrocardiogramme',
                'categorie' => 'autre',
                'type' => 'Examen médical',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 7000.00,
                'frequence_plafond' => 'par examen',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'ES01',
                'designation' => 'Echographie standard',
                'categorie' => 'autre',
                'type' => 'Echographie',
                'sous_type' => 'standard',
                'taux_remboursement' => 80,
                'plafond_remboursement' => 15000.00,
                'frequence_plafond' => 'par échographie',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'SCN01',
                'designation' => 'Scanner',
                'categorie' => 'radiologie',
                'type' => 'Scanner',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 40000.00,
                'frequence_plafond' => 'par scanner',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'FP01',
                'designation' => 'Frais pharmaceutiques (pharmacies)',
                'categorie' => 'pharmacie',
                'type' => 'Pharmacie',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 300000.00,
                'frequence_plafond' => 'par an',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'KR01',
                'designation' => 'Kinésithérapie et rééducation',
                'categorie' => 'autre',
                'type' => 'Rééducation',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 25000.00,
                'frequence_plafond' => 'par an',
                'beneficiaire' => 'famille',
            ],
            [
                'id' => Str::uuid(),
                'code' => 'FRM01',
                'designation' => 'Frais de recherche médicale',
                'categorie' => 'autre',
                'type' => 'Frais de recherche médicale',
                'sous_type' => null,
                'taux_remboursement' => 80,
                'plafond_remboursement' => 100000.00,
                'frequence_plafond' => 'par an',
                'beneficiaire' => 'famille',
            ],
        ]);
    }
}
